### ISSUE TITLE
What are the "images_icons" names of AMD and ATI ???

### ISSUE THREAD

**Issue by LRF520** [Gokender/minotorr#1]
The "images_icons" name of Intel integrated graphics card is "Intel. png", and the "images_icons" name of NVIDIA independent graphics card is "nvidia. png". I would like to ask the following four questions. Please give me your advice. Thank you:

(1) What is the "images_icons" name of AMD integrated graphics card?

(2) What is the "images_icons" name of AMD independent graphics card?

(3) What is the "images_icons" name of ATI integrated graphics card?

(4) What is the "images_icons" name of the ATI independent graphics card?

**Comment by gokender** [comment]
Hello, sorry for the delay in responding, it's been a while since I've worked on this project.

You can find some answers in the LibreHardwareMonitor project on which I base myself, and more particularly on this [page](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/blob/627f0a56ce1c7b5b442b8e72d12309c49be651ea/LibreHardwareMonitor/UI/HardwareTypeImage.cs)

I don't use images in this project.

I hope I could help.
